storagenetwork = false
tconstruct = false
fastfurnaceminusreplacement = true
sophisticatedbackpacks = false
fastfurnace = true
craftingstation = true
ironfurnaces = true
occultism = false
jei = true
extendedcrafting = true
fastbenchminusreplacement = true
refinedstorageaddons = false
craftingcraft = false
toms_storage = false
refinedstorage = false
prettypipes = false
fastbench = true
cyclic = false
appliedenergistics2 = true

