
#Misc Ring Settings
[misc_ring_settings]
	#Uses a delayed break mode to reduce stutter and potential lag [true / false]
	delayedBreakMode = false
	#Reverse the drop/no drops feature on Ring of Miner [true / false]
	reverseRingMiner = false
	#Number of ticks duration for the Ring of the Miner cooldown [0-240, default: 80]
	#Range: 0 ~ 120
	ringMinerCooldown = 80

