//Remove recipes for The Ultimate Block so only ours will be available later on
craftingTable.removeRecipe(<item:extendedcrafting:the_ultimate_block>);

//Remove recipe for The Ultimate Ingot so only ours will be available later on
craftingTable.removeRecipe(<item:extendedcrafting:the_ultimate_ingot>);

//Remove recipe for The Ultimate Nugget so only ours will be available later on
craftingTable.removeRecipe(<item:extendedcrafting:the_ultimate_nugget>);

//Immersive Engineering Creative Capacitor
mods.extendedcrafting.TableCrafting.addShaped("capacitor_creative", 4, <item:immersiveengineering:capacitor_creative>, [
	[<item:appliedenergistics2:quartz_growth_accelerator>, <item:appliedenergistics2:energy_cell>, <item:appliedenergistics2:energy_cell>, <item:appliedenergistics2:crafting_accelerator>, <item:minecraft:beacon>, <item:immersiveengineering:storage_uranium>, <item:immersiveengineering:dynamo>, <item:immersiveengineering:sorter>, <item:immersiveengineering:capacitor_lv>], 
	[<item:appliedenergistics2:dense_energy_cell>, <item:appliedenergistics2:1k_crafting_storage>, <item:appliedenergistics2:4k_crafting_storage>, <item:appliedenergistics2:energy_cell>, <item:pamhc2foodextended:chimichangaitem>, <item:immersiveengineering:watermill>, <item:immersiveengineering:connector_mv>, <item:immersiveengineering:capacitor_mv>, <item:immersiveengineering:item_batcher>], 
	[<item:appliedenergistics2:dense_energy_cell>, <item:appliedenergistics2:16k_crafting_storage>, <item:appliedenergistics2:64k_crafting_storage>, <item:appliedenergistics2:energy_cell>, <item:pamhc2foodextended:supremepizzaitem>, <item:immersiveengineering:transformer>, <item:immersiveengineering:capacitor_hv>, <item:immersiveengineering:connector_mv_relay>, <item:immersiveengineering:windmill>], 
	[<item:appliedenergistics2:crafting_monitor>, <item:appliedenergistics2:dense_energy_cell>, <item:appliedenergistics2:dense_energy_cell>, <item:appliedenergistics2:energy_acceptor>, <item:pamhc2foodcore:epicbaconitem>, <item:immersiveengineering:connector_hv_relay>, <item:immersiveengineering:transformer_hv>, <item:immersiveengineering:thermoelectric_generator>, <item:immersiveengineering:fluid_sorter>], 
	[<item:mysticalagriculture:master_infusion_crystal>, <item:pamhc2foodextended:chimichangaitem>, <item:pamhc2foodextended:supremepizzaitem>, <item:pamhc2foodcore:epicbaconitem>, <item:extendedcrafting:ultimate_singularity>, <item:pamhc2foodcore:epicbaconitem>, <item:pamhc2foodextended:supremepizzaitem>, <item:pamhc2foodextended:chimichangaitem>, <item:storagedrawers:emerald_storage_upgrade>], 
	[<item:bigreactors:reinforced_turbinecomputerport>, <item:bigreactors:reinforced_turbineglass>, <item:bigreactors:reinforced_turbinecontroller>, <item:bigreactors:reinforced_turbinecasing>, <item:pamhc2foodcore:epicbaconitem>, <item:create:large_cogwheel>, <item:create:encased_fan>, <item:create:deployer>, <item:create:rope_pulley>], 
	[<item:bigreactors:reinforced_turbinerotorshaft>, <item:bigreactors:reinforced_turbinerotorbearing>, <item:bigreactors:reinforced_reactorcasing>, <item:bigreactors:basic_reactorcontroller>, <item:pamhc2foodextended:supremepizzaitem>, <item:create:water_wheel>, <item:create:crushing_wheel>, <item:create:encased_chain_drive>, <item:create:gearbox>], 
	[<item:bigreactors:reinforced_turbinerotorblade>, <item:bigreactors:cyanite_block>, <item:bigreactors:reinforced_reactorcontrolrod>, <item:bigreactors:reinforced_reactorglass>, <item:pamhc2foodextended:chimichangaitem>, <item:create:mechanical_saw>, <item:create:adjustable_chain_gearshift>, <item:create:millstone>, <item:create:clutch>], 
	[<item:bigreactors:yellorium_block>, <item:bigreactors:reinforced_reactorfuelrod>, <item:bigreactors:reinforced_reactorredstoneport>, <item:bigreactors:reinforced_reactorcomputerport>, <item:minecraft:dragon_egg>, <item:create:mechanical_drill>, <item:create:vertical_gearbox>, <item:create:gearshift>, <item:create:mechanical_pump>]]);

// Create Creative Fluid Tank
mods.extendedcrafting.TableCrafting.addShaped("creative_fluid_tank", 2, <item:create:creative_fluid_tank>, [
	[<item:create:fluid_valve>, <item:create:fluid_valve>, <item:create:fluid_tank>, <item:create:fluid_valve>, <item:create:fluid_valve>], 
	[<item:create:mechanical_pump>, <item:create:mechanical_pump>, <item:create:fluid_tank>, <item:create:mechanical_pump>, <item:create:mechanical_pump>], 
	[<item:create:fluid_tank>, <item:create:fluid_tank>, <item:extendedcrafting:ultimate_singularity>, <item:create:fluid_tank>, <item:create:fluid_tank>], 
	[<item:create:smart_fluid_pipe>, <item:create:smart_fluid_pipe>, <item:create:fluid_tank>, <item:create:smart_fluid_pipe>, <item:create:smart_fluid_pipe>], 
	[<item:create:portable_fluid_interface>, <item:create:water_wheel>, <item:create:fluid_tank>, <item:create:water_wheel>, <item:create:portable_fluid_interface>]]);

//Create Creative Motor
mods.extendedcrafting.TableCrafting.addShaped("creative_motor", 3, <item:create:creative_motor>, [
	[<item:create:cogwheel>, <item:create:cogwheel>, <item:create:refined_radiance_casing>, <item:create:crushing_wheel>, <item:create:refined_radiance_casing>, <item:create:cogwheel>, <item:create:cogwheel>], 
	[<item:create:cogwheel>, <item:create:speedometer>, <item:create:large_cogwheel>, <item:create:rotation_speed_controller>, <item:create:large_cogwheel>, <item:create:flywheel>, <item:create:cogwheel>], 
	[<item:create:refined_radiance_casing>, <item:create:large_cogwheel>, <item:create:clutch>, <item:create:water_wheel>, <item:create:gearshift>, <item:create:large_cogwheel>, <item:create:refined_radiance_casing>], 
	[<item:create:millstone>, <item:create:rotation_speed_controller>, <item:create:water_wheel>, <item:extendedcrafting:ultimate_singularity>, <item:create:water_wheel>, <item:create:rotation_speed_controller>, <item:create:mechanical_press>], 
	[<item:create:refined_radiance_casing>, <item:create:large_cogwheel>, <item:create:adjustable_chain_gearshift>, <item:create:water_wheel>, <item:create:encased_chain_drive>, <item:create:large_cogwheel>, <item:create:refined_radiance_casing>], 
	[<item:create:cogwheel>, <item:create:flywheel>, <item:create:large_cogwheel>, <item:create:rotation_speed_controller>, <item:create:large_cogwheel>, <item:create:stressometer>, <item:create:cogwheel>], 
	[<item:create:cogwheel>, <item:create:cogwheel>, <item:create:refined_radiance_casing>, <item:create:mechanical_mixer>, <item:create:refined_radiance_casing>, <item:create:cogwheel>, <item:create:cogwheel>]]);

//Applied Energistics Creative Energy Cell
mods.extendedcrafting.TableCrafting.addShaped("creative_energy_cell", 2, <item:appliedenergistics2:creative_energy_cell>, [
	[<item:appliedenergistics2:dense_energy_cell>, <item:appliedenergistics2:dense_energy_cell>, <item:appliedenergistics2:quartz_growth_accelerator>, <item:appliedenergistics2:dense_energy_cell>, <item:appliedenergistics2:dense_energy_cell>], 
	[<item:appliedenergistics2:dense_energy_cell>, <item:appliedenergistics2:singularity>, <item:appliedenergistics2:name_press>, <item:appliedenergistics2:singularity>, <item:appliedenergistics2:dense_energy_cell>], 
	[<item:appliedenergistics2:engineering_processor_press>, <item:appliedenergistics2:logic_processor_press>, <item:extendedcrafting:ultimate_singularity>, <item:appliedenergistics2:calculation_processor_press>, <item:appliedenergistics2:silicon_press>], 
	[<item:appliedenergistics2:dense_energy_cell>, <item:appliedenergistics2:64k_cell_component>, <item:appliedenergistics2:64k_fluid_cell_component>, <item:appliedenergistics2:128_cubed_spatial_cell_component>, <item:appliedenergistics2:dense_energy_cell>], 
	[<item:appliedenergistics2:dense_energy_cell>, <item:appliedenergistics2:dense_energy_cell>, <item:appliedenergistics2:quartz_growth_accelerator>, <item:appliedenergistics2:dense_energy_cell>, <item:appliedenergistics2:dense_energy_cell>]]);

//Extended Crafting Ultimate Block
mods.extendedcrafting.TableCrafting.addShaped("the_ultimate_block", 4, <item:extendedcrafting:the_ultimate_block>, [
	[<item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:crystaltine_block>, <item:extendedcrafting:crystaltine_block>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:nether_star_block>, <item:extendedcrafting:nether_star_block>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ultimate_singularity>], 
	[<item:extendedcrafting:ender_star>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:ender_star>], 
	[<item:extendedcrafting:enhanced_ender_ingot_block>, <item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:ender_star_block>], 
	[<item:extendedcrafting:enhanced_ender_ingot_block>, <item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:advanced_auto_table>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:ender_star_block>], 
	[<item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:elite_auto_table>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:ultimate_singularity>], 
	[<item:extendedcrafting:ender_ingot_block>, <item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:ultimate_auto_table>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:redstone_ingot_block>], 
	[<item:extendedcrafting:ender_ingot_block>, <item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:redstone_ingot_block>], 
	[<item:extendedcrafting:ender_star>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:ender_star>], 
	[<item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:luminessence_block>, <item:extendedcrafting:luminessence_block>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:black_iron_block>, <item:extendedcrafting:black_iron_block>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ultimate_singularity>]]);

//Extended Crafting The Ultimate Ingot
mods.extendedcrafting.TableCrafting.addShaped("the_ultimate_ingot", 4, <item:extendedcrafting:the_ultimate_ingot>, [
	[<item:extendedcrafting:black_iron_ingot>, <item:extendedcrafting:black_iron_ingot>, <item:extendedcrafting:black_iron_ingot>, <item:extendedcrafting:black_iron_ingot>, <item:extendedcrafting:black_iron_ingot>, <item:extendedcrafting:black_iron_ingot>, <item:extendedcrafting:black_iron_ingot>, <item:extendedcrafting:black_iron_ingot>, <item:extendedcrafting:black_iron_ingot>], 
	[<item:extendedcrafting:black_iron_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:black_iron_ingot>], 
	[<item:extendedcrafting:black_iron_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:enhanced_ender_ingot>, <item:extendedcrafting:enhanced_ender_ingot>, <item:extendedcrafting:enhanced_ender_ingot>, <item:extendedcrafting:enhanced_ender_ingot>, <item:extendedcrafting:enhanced_ender_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:black_iron_ingot>], 
	[<item:extendedcrafting:black_iron_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:enhanced_ender_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:enhanced_ender_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:black_iron_ingot>], 
	[<item:extendedcrafting:black_iron_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:enhanced_ender_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:enhanced_ender_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:black_iron_ingot>], 
	[<item:extendedcrafting:black_iron_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:enhanced_ender_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:enhanced_ender_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:black_iron_ingot>], 
	[<item:extendedcrafting:black_iron_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:enhanced_ender_ingot>, <item:extendedcrafting:enhanced_ender_ingot>, <item:extendedcrafting:enhanced_ender_ingot>, <item:extendedcrafting:enhanced_ender_ingot>, <item:extendedcrafting:enhanced_ender_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:black_iron_ingot>], 
	[<item:extendedcrafting:black_iron_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:black_iron_ingot>], 
	[<item:extendedcrafting:black_iron_ingot>, <item:extendedcrafting:black_iron_ingot>, <item:extendedcrafting:black_iron_ingot>, <item:extendedcrafting:black_iron_ingot>, <item:extendedcrafting:black_iron_ingot>, <item:extendedcrafting:black_iron_ingot>, <item:extendedcrafting:black_iron_ingot>, <item:extendedcrafting:black_iron_ingot>, <item:extendedcrafting:black_iron_ingot>]]);

//Extended Craftin The Ultimate Nugget
mods.extendedcrafting.TableCrafting.addShaped("the_ultimate_nugget", 4, <item:extendedcrafting:the_ultimate_nugget>, [
	[<item:extendedcrafting:black_iron_nugget>, <item:extendedcrafting:black_iron_nugget>, <item:extendedcrafting:black_iron_nugget>, <item:extendedcrafting:black_iron_nugget>, <item:extendedcrafting:black_iron_nugget>, <item:extendedcrafting:black_iron_nugget>, <item:extendedcrafting:black_iron_nugget>, <item:extendedcrafting:black_iron_nugget>, <item:extendedcrafting:black_iron_nugget>], 
	[<item:extendedcrafting:black_iron_nugget>, <item:extendedcrafting:redstone_nugget>, <item:extendedcrafting:redstone_nugget>, <item:extendedcrafting:redstone_nugget>, <item:extendedcrafting:redstone_nugget>, <item:extendedcrafting:redstone_nugget>, <item:extendedcrafting:redstone_nugget>, <item:extendedcrafting:redstone_nugget>, <item:extendedcrafting:black_iron_nugget>], 
	[<item:extendedcrafting:black_iron_nugget>, <item:extendedcrafting:redstone_nugget>, <item:extendedcrafting:enhanced_ender_nugget>, <item:extendedcrafting:enhanced_ender_nugget>, <item:extendedcrafting:enhanced_ender_nugget>, <item:extendedcrafting:enhanced_ender_nugget>, <item:extendedcrafting:enhanced_ender_nugget>, <item:extendedcrafting:redstone_nugget>, <item:extendedcrafting:black_iron_nugget>], 
	[<item:extendedcrafting:black_iron_nugget>, <item:extendedcrafting:redstone_nugget>, <item:extendedcrafting:enhanced_ender_nugget>, <item:extendedcrafting:crystaltine_nugget>, <item:extendedcrafting:crystaltine_nugget>, <item:extendedcrafting:crystaltine_nugget>, <item:extendedcrafting:ender_nugget>, <item:extendedcrafting:redstone_nugget>, <item:extendedcrafting:black_iron_nugget>], 
	[<item:extendedcrafting:black_iron_nugget>, <item:extendedcrafting:redstone_nugget>, <item:extendedcrafting:enhanced_ender_nugget>, <item:extendedcrafting:crystaltine_nugget>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:crystaltine_nugget>, <item:extendedcrafting:ender_nugget>, <item:extendedcrafting:redstone_nugget>, <item:extendedcrafting:black_iron_nugget>], 
	[<item:extendedcrafting:black_iron_nugget>, <item:extendedcrafting:redstone_nugget>, <item:extendedcrafting:enhanced_ender_nugget>, <item:extendedcrafting:crystaltine_nugget>, <item:extendedcrafting:crystaltine_nugget>, <item:extendedcrafting:crystaltine_nugget>, <item:extendedcrafting:ender_nugget>, <item:extendedcrafting:redstone_nugget>, <item:extendedcrafting:black_iron_nugget>], 
	[<item:extendedcrafting:black_iron_nugget>, <item:extendedcrafting:redstone_nugget>, <item:extendedcrafting:ender_nugget>, <item:extendedcrafting:ender_nugget>, <item:extendedcrafting:ender_nugget>, <item:extendedcrafting:ender_nugget>, <item:extendedcrafting:ender_nugget>, <item:extendedcrafting:redstone_nugget>, <item:extendedcrafting:black_iron_nugget>], 
	[<item:extendedcrafting:black_iron_nugget>, <item:extendedcrafting:redstone_nugget>, <item:extendedcrafting:redstone_nugget>, <item:extendedcrafting:redstone_nugget>, <item:extendedcrafting:redstone_nugget>, <item:extendedcrafting:redstone_nugget>, <item:extendedcrafting:redstone_nugget>, <item:extendedcrafting:redstone_nugget>, <item:extendedcrafting:black_iron_nugget>], 
	[<item:extendedcrafting:black_iron_nugget>, <item:extendedcrafting:black_iron_nugget>, <item:extendedcrafting:black_iron_nugget>, <item:extendedcrafting:black_iron_nugget>, <item:extendedcrafting:black_iron_nugget>, <item:extendedcrafting:black_iron_nugget>, <item:extendedcrafting:black_iron_nugget>, <item:extendedcrafting:black_iron_nugget>, <item:extendedcrafting:black_iron_nugget>]]);

//Create Creative Crate
mods.extendedcrafting.TableCrafting.addShaped("creative_crate", 4, <item:create:creative_crate>, [
	[<item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:the_ultimate_ingot>, <item:create:creative_fluid_tank>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:the_ultimate_nugget>], 
	[<item:extendedcrafting:the_ultimate_nugget>, <item:storagedrawers:gold_storage_upgrade>, <item:extendedcrafting:frame>, <item:extendedcrafting:nether_star_block>, <item:bigreactors:reinforced_reactorcreativewatergenerator>, <item:extendedcrafting:nether_star_block>, <item:extendedcrafting:frame>, <item:ae2extras:1m_cell_component>, <item:extendedcrafting:the_ultimate_nugget>], 
	[<item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:frame>, <item:storagedrawers:diamond_storage_upgrade>, <item:bigreactors:basic_turbinecreativesteamgenerator>, <item:immersiveengineering:capacitor_creative>, <item:appliedenergistics2:creative_energy_cell>, <item:ae2extras:4m_cell_component>, <item:extendedcrafting:frame>, <item:extendedcrafting:the_ultimate_nugget>], 
	[<item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:nether_star_block>, <item:bigreactors:reinforced_turbinecreativesteamgenerator>, <item:storagedrawers:emerald_storage_upgrade>, <item:extendedcrafting:ultimate_singularity>, <item:ae2extras:16m_cell_component>, <item:create:creative_motor>, <item:extendedcrafting:nether_star_block>, <item:extendedcrafting:the_ultimate_ingot>], 
	[<item:extendedcrafting:ender_star_block>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:the_ultimate_block>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:ender_star_block>], 
	[<item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:nether_star_block>, <item:extendedcrafting:frame>, <item:ironchest:obsidian_chest>, <item:extendedcrafting:ultimate_singularity>, <item:enderstorage:ender_chest>, <item:extendedcrafting:frame>, <item:extendedcrafting:nether_star_block>, <item:extendedcrafting:the_ultimate_ingot>], 
	[<item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:frame>, <item:ironchest:crystal_chest>, <item:extendedcrafting:frame>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:frame>, <item:appliedenergistics2:chest>, <item:extendedcrafting:frame>, <item:extendedcrafting:the_ultimate_nugget>], 
	[<item:extendedcrafting:the_ultimate_nugget>, <item:ironchest:dirt_chest>, <item:extendedcrafting:frame>, <item:extendedcrafting:nether_star_block>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:nether_star_block>, <item:extendedcrafting:frame>, <item:usefulbackpacks:backpack_enderchest>, <item:extendedcrafting:the_ultimate_nugget>], 
	[<item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:ender_star_block>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:the_ultimate_nugget>, <item:extendedcrafting:the_ultimate_nugget>]]);

//Extreme Reactors 
//Reinforced Creative Water Generator
mods.extendedcrafting.TableCrafting.addShaped("reinforced_reactorcreativewatergenerator", 3, <item:bigreactors:reinforced_reactorcreativewatergenerator>, [
	[<item:bigreactors:cyanite_block>, <item:bigreactors:basic_reactorcontroller>, <item:bigreactors:cyanite_block>, <item:bigreactors:basic_reactorfuelrod>, <item:bigreactors:cyanite_block>, <item:bigreactors:basic_reactorcontrolrod>, <item:bigreactors:cyanite_block>], 
	[<item:bigreactors:basic_reactorglass>, <item:bigreactors:cyanite_block>, <item:bigreactors:reinforced_reactorcontrolrod>, <item:bigreactors:cyanite_block>, <item:bigreactors:reinforced_reactorsolidaccessport>, <item:bigreactors:cyanite_block>, <item:bigreactors:basic_reactorsolidaccessport>], 
	[<item:bigreactors:cyanite_block>, <item:bigreactors:reinforced_reactorfuelrod>, <item:bigreactors:cyanite_block>, <item:bigreactors:reinforced_reactorfluidport_forge_passive>, <item:bigreactors:cyanite_block>, <item:bigreactors:reinforced_reactorpowertapfe_active>, <item:bigreactors:cyanite_block>], 
	[<item:bigreactors:basic_reactorcasing>, <item:bigreactors:cyanite_block>, <item:bigreactors:reinforced_reactorfluidport_forge_active>, <item:extendedcrafting:ultimate_singularity>, <item:bigreactors:reinforced_reactorfluidport_mekanism_passive>, <item:bigreactors:cyanite_block>, <item:bigreactors:basic_reactorpowertapfe_active>], 
	[<item:bigreactors:cyanite_block>, <item:bigreactors:reinforced_reactorcontroller>, <item:bigreactors:cyanite_block>, <item:bigreactors:reinforced_reactorchargingportfe>, <item:bigreactors:cyanite_block>, <item:bigreactors:reinforced_reactorpowertapfe_passive>, <item:bigreactors:cyanite_block>], 
	[<item:bigreactors:reinforced_reactorglass>, <item:bigreactors:cyanite_block>, <item:bigreactors:reinforced_reactorredstoneport>, <item:bigreactors:cyanite_block>, <item:bigreactors:reinforced_reactorcomputerport>, <item:bigreactors:cyanite_block>, <item:bigreactors:basic_reactorpowertapfe_passive>], 
	[<item:bigreactors:cyanite_block>, <item:bigreactors:reinforced_reactorcasing>, <item:bigreactors:cyanite_block>, <item:bigreactors:basic_reactorchargingportfe>, <item:bigreactors:cyanite_block>, <item:bigreactors:basic_reactorredstoneport>, <item:bigreactors:cyanite_block>]]);

//Turbine Creative Steam Generator Basic
mods.extendedcrafting.TableCrafting.addShaped("basic_turbinecreativesteamgenerator", 2, <item:bigreactors:basic_turbinecreativesteamgenerator>, [
	[<item:bigreactors:cyanite_block>, <item:bigreactors:basic_turbineglass>, <item:bigreactors:cyanite_block>, <item:bigreactors:basic_turbinecontroller>, <item:bigreactors:cyanite_block>], 
	[<item:bigreactors:basic_turbinecasing>, <item:bigreactors:cyanite_block>, <item:bigreactors:basic_turbinefluidport_forge_passive>, <item:bigreactors:cyanite_block>, <item:bigreactors:basic_turbinerotorbearing>], 
	[<item:bigreactors:cyanite_block>, <item:bigreactors:basic_turbinefluidport_forge_active>, <item:extendedcrafting:ultimate_singularity>, <item:bigreactors:basic_turbinecreativesteamgenerator>, <item:bigreactors:cyanite_block>], 
	[<item:bigreactors:basic_turbinepowertapfe_passive>, <item:bigreactors:cyanite_block>, <item:bigreactors:basic_turbinechargingportfe>, <item:bigreactors:cyanite_block>, <item:bigreactors:basic_turbinerotorshaft>], 
	[<item:bigreactors:cyanite_block>, <item:bigreactors:basic_turbinepowertapfe_active>, <item:bigreactors:cyanite_block>, <item:bigreactors:basic_turbinerotorblade>, <item:bigreactors:cyanite_block>]]);

//Turbine Creative Steam Generator Reinforced
mods.extendedcrafting.TableCrafting.addShaped("reinforced_turbinecreativesteamgenerator", 0, <item:bigreactors:reinforced_turbinecreativesteamgenerator>, [
	[<item:bigreactors:cyanite_block>, <item:bigreactors:reinforced_turbinecontroller>, <item:bigreactors:cyanite_block>, <item:bigreactors:reinforced_turbinerotorbearing>, <item:bigreactors:cyanite_block>], 
	[<item:bigreactors:reinforced_turbineglass>, <item:bigreactors:cyanite_block>, <item:bigreactors:reinforced_turbinefluidport_forge_passive>, <item:bigreactors:cyanite_block>, <item:bigreactors:reinforced_turbinerotorshaft>], 
	[<item:bigreactors:cyanite_block>, <item:bigreactors:reinforced_turbinefluidport_forge_active>, <item:extendedcrafting:ultimate_singularity>, <item:bigreactors:reinforced_turbinecomputerport>, <item:bigreactors:cyanite_block>], 
	[<item:bigreactors:reinforced_turbinecasing>, <item:bigreactors:cyanite_block>, <item:bigreactors:reinforced_turbinechargingportfe>, <item:bigreactors:cyanite_block>, <item:bigreactors:reinforced_turbinerotorblade>], 
	[<item:bigreactors:cyanite_block>, <item:bigreactors:reinforced_turbinepowertapfe_passive>, <item:bigreactors:cyanite_block>, <item:bigreactors:reinforced_turbinepowertapfe_active>, <item:bigreactors:cyanite_block>]]);

//The One Probe Creative Probe
mods.extendedcrafting.TableCrafting.addShaped("creativeprobe", 0, <item:theoneprobe:creativeprobe>, [
	[<item:extendedcrafting:ender_nugget>, <item:extendedcrafting:ender_nugget>, <item:extendedcrafting:ender_nugget>], 
	[<item:extendedcrafting:ender_nugget>, <item:theoneprobe:probe>, <item:extendedcrafting:ender_nugget>], 
	[<item:extendedcrafting:ender_nugget>, <item:extendedcrafting:ender_nugget>, <item:extendedcrafting:ender_nugget>]]);